### ISSUE TITLE
If a spec does not end in a newline, the last entry will not be processed

### ISSUE THREAD

**Issue by cblichmann** [cblichmann/jailtime#6]
See title, example file:
```
/usr/bin/git
/usr/bin/git-shell
/usr/bin/git-upload-pack | <- No newline here
```

This will only include the first two entries in the chroot target dir.

**Comment by empijei** [comment]
For the authors/maintainers: This is because a bufio.Reader is used instead of a bufio.Scanner [here](https://github.com/cblichmann/jailtime/blob/master/spec/parser.go#L141) and when the reader returns io.EOF the output is ignored, but it should not be as stated [here](https://golang.org/pkg/bufio/#Reader.ReadString).

file: `parser.go`
```go
	for lineNo := 1; ; lineNo++ {
		line, err = r.ReadString('\n')
		if err == io.EOF {
			err = nil
//IGNORING line here
			break
		} else if err != nil {
			return
		}
```
I suggest using a [scanner](https://golang.org/pkg/bufio/#NewScanner) instead, that not just grants to read all tokens in the file but also strips '\r' after '\n' in case the file has windows lineendings.
